/**
 * 거래처 Store
 */
Ext.define('Smartax.store.basic.CompanyInfoStore', {
	extend: 'Ext.data.Store',
	storeId: 'companyInfoStore',
	fields: [
			{name: 'co_id', type: 'string'},
			{name: 'co_nm', type: 'string'},
			{name: 'co_ceo_nm', type: 'string'},
			{name: 'co_saup_no', type: 'string'},
			{name: 'co_co_no', type: 'string'},
			{name: 'co_up', type: 'string'},
			{name: 'co_jong', type: 'string'},
			{name: 'co_addr', type: 'string'},
			{name: 'co_tel', type: 'string'},
			{name: 'co_handphone', type: 'string'},
			{name: 'co_email', type: 'string'},
			{name: 'co_tax_office', type: 'string'},
			{name: 'co_tax_office_code', type: 'string'},
			{name: 'co_tax_office_acc', type: 'string'},
			{name: 'co_bank', type: 'string'},
			{name: 'co_bank_branch', type: 'string'},
			{name: 'co_bank_acc', type: 'string'},
			{name: 'co_tax_type', type: 'string'},
			{name: 'tax_type', type: 'string'},
			{name: 'co_config', type: 'string'},
			{name: 'hometax_id', type: 'string'},
			{name: 'hometax_pwd', type: 'string'},
			{name: 'co_joint', type: 'string'},
			{name: 'co_lease', type: 'string'},
			{name: 'co_area', type: 'string'},
			{name: 'co_building_upstairs', type: 'int'},
			{name: 'co_building_downstairs', type: 'int'},
			{name: 'co_building_t_area', type: 'string'},
			{name: 'co_building_area', type: 'string'},
			{name: 'co_room_cnt', type: 'string'},
			{name: 'co_table_cnt', type: 'string'},
			{name: 'co_is_parking_area', type: 'string'},
			{name: 'co_vehicle_car', type: 'int'},
			{name: 'co_vehicle_truck', type: 'int'},
			{name: 'co_vehicle_business', type: 'int'},
			{name: 'co_employee_cnt', type: 'int'},
			{name: 'co_chair_cnt', type: 'int'},
			{name: 'co_etc_bigo', type: 'string'},
			{name: 'co_expense_deposit', type: 'int'},
			{name: 'co_expense_m_rent', type: 'int'},
			{name: 'co_expense_elect', type: 'int'},
			{name: 'co_expense_water', type: 'int'},
			{name: 'co_expense_man', type: 'int'},
			{name: 'co_expense_etc', type: 'int'},
		]
   
});
